### PR TITLE
Use v1beta1 RouteTable

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

provider-aws no longer provides v1alpha4 RouteTable, instead providing
v1beta1. This updates to use the new version.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

Built, pushed, installed, then create a `CompositeNetwork`. All resources were create successfully:
```
🤖 (platform-ref-multi-k8s) k get aws
NAME                                                   READY   SYNCED   ID                     VPC                     AGE
securitygroup.ec2.aws.crossplane.io/my-network-9ftk9   True    True     sg-096563dcb24cf49df   vpc-0bf256467c80e9192   6h16m

NAME                                                READY   SYNCED   ID                      VPC                     AGE
routetable.ec2.aws.crossplane.io/my-network-4scjr   True    True     rtb-0aca9804a03cc785d   vpc-0bf256467c80e9192   26m

NAME                                                     READY   SYNCED   ID                      VPC                     AGE
internetgateway.ec2.aws.crossplane.io/my-network-ckdl6   True    True     igw-027076947a090cd0d   vpc-0bf256467c80e9192   6h16m

NAME                                            READY   SYNCED   ID                         VPC                     CIDR               AGE
subnet.ec2.aws.crossplane.io/my-network-69wf4   True    True     subnet-0e1c7ab5ec7545491   vpc-0bf256467c80e9192   192.168.192.0/18   6h16m
subnet.ec2.aws.crossplane.io/my-network-9fbm9   True    True     subnet-094e7605afe2e8c74   vpc-0bf256467c80e9192   192.168.64.0/18    6h16m
subnet.ec2.aws.crossplane.io/my-network-lgnl9   True    True     subnet-082ea8e3cb2d7020a   vpc-0bf256467c80e9192   192.168.0.0/18     6h16m
subnet.ec2.aws.crossplane.io/my-network-qg8t7   True    True     subnet-0c383a03deedf8207   vpc-0bf256467c80e9192   192.168.128.0/18   6h16m

NAME                                         READY   SYNCED   ID                      CIDR             AGE
vpc.ec2.aws.crossplane.io/my-network-424rr   True    True     vpc-0bf256467c80e9192   192.168.0.0/16   6h16m

NAME                                                                         AGE     CONFIG-NAME   RESOURCE-KIND     RESOURCE-NAME
providerconfigusage.aws.crossplane.io/29500578-c890-4f10-9a7d-20d203783ece   6h3m    default       Subnet            my-network-lgnl9
providerconfigusage.aws.crossplane.io/4ad65141-c96d-424b-a7e0-bc6c75493669   6h3m    default       Subnet            my-network-qg8t7
providerconfigusage.aws.crossplane.io/73579a43-e6f2-4477-9c1f-b988fbd6a6dd   6h3m    default       Subnet            my-network-9fbm9
providerconfigusage.aws.crossplane.io/78d9a496-d318-4c3f-9e11-f4d521676b83   6h3m    default       InternetGateway   my-network-ckdl6
providerconfigusage.aws.crossplane.io/a47ce636-505d-4a1d-86f1-41a9a3e89168   6h3m    default       Subnet            my-network-69wf4
providerconfigusage.aws.crossplane.io/b3aefaba-9f98-4bdc-9074-2763873b3b88   26m     default       RouteTable        my-network-4scjr
providerconfigusage.aws.crossplane.io/c4b930cc-0333-4ce1-ae8a-10541490a496   6h3m    default       SecurityGroup     my-network-9ftk9
providerconfigusage.aws.crossplane.io/d9fc2ef5-c58b-456a-a645-c1f915d38eac   6h13m   default       VPC               my-network-424rr

NAME                                       AGE
providerconfig.aws.crossplane.io/default   6h14m
```

### CODE REVIEW

**Review by jbw976 — APPROVED** [review]
Thanks for getting to the bottom of this and fixing it @hasheddan :)

**Comment by jbw976** [comment]
Would we have the same issue in other reference platforms too?

**Comment by hasheddan** [comment]
@jbw976 potentially so! I'll look through each and update if necessary!

Also, could you either add me with merge permissions to this repo or go ahead and merge it yourself if preferred? Looks like I don't have permissions :)

**Comment by jbw976** [comment]
I've gone ahead and merged this in, but also given you maintainer access to all 4 platform-ref-* repos @hasheddan :)

**Pull request merged**
